export const supermarketItems = [
  // Fruits
  "Apple", "Apples",
  "Banana", "Bananas",
  "Orange", "Oranges",
  "Grape", "Grapes",
  "Lemon", "Lemons",
  "Strawberry", "Strawberries",
  "Blueberry", "Blueberries",
  "Pineapple", "Pineapples",
  "Mango", "Mangoes",
  "Peach", "Peaches",
  "Watermelon", "Watermelons",
  "Cantaloupe", "Cantaloupes",
  "Avocado", "Avocados",

  // Vegetables
  "Tomato", "Tomatoes",
  "Potato", "Potatoes",
  "Onion", "Onions",
  "Carrot", "Carrots",
  "Broccoli", "Broccolis",
  "Spinach", "Spinaches",
  "Lettuce", "Lettuces",
  "Kale", "Kales",
  "Cucumber", "Cucumbers",
  "Bell pepper", "Bell peppers",
  "Zucchini", "Zucchinis",
  "Eggplant", "Eggplants",
  "Mushroom", "Mushrooms",
  "Garlic", "Garlics",
  "Ginger", "Gingers",
  "Sweet potato", "Sweet potatoes",
  "Green bean", "Green beans",
  "Asparagus", "Asparaguses",
  "Cauliflower", "Cauliflowers",
  "Celery", "Celeries",
  "Pea", "Peas",
  "Corn", "Corns",
  "Corn on the cob", "Corns on the cob",
  "Cabbage", "Cabbages",
  "Brussels sprout", "Brussels sprouts",
  "Radish", "Radishes",
  "Beet", "Beets",
  "Squash", "Squashes",
  "Butternut squash", "Butternut squashes",
  "Pumpkin", "Pumpkins",
  "Yam", "Yams",
  "Artichoke", "Artichokes",
  "Arugula", "Arugulas",
  "Bok choy", "Bok choys",
  "Chard", "Chards",
  "Collard green", "Collard greens",
  "Endive", "Endives",
  "Fennel", "Fennels",
  "Leek", "Leeks",
  "Okra", "Okras",
  "Parsnip", "Parsnips",
  "Rutabaga", "Rutabagas",
  "Scallion", "Scallions",
  "Shallot", "Shallots",
  "Turnip", "Turnips",
  "Watercress", "Watercresses",

  // Dairy & Alternatives
  "Tofu", "Tofus",
  "Almond milk", "Almond milks",
  "Cow's milk", "Cow's milks",
  "Soy milk", "Soy milks",
  "Rice milk", "Rice milks",
  "Cheese", "Cheeses",
  "Yogurt", "Yogurts",
  "Butter", "Butters",
  "Cream cheese", "Cream cheeses",
  "Ice cream", "Ice creams",

  // Frozen Foods
  "Frozen pizza", "Frozen pizzas",
  "Frozen vegetable", "Frozen vegetables",
  "Frozen berry", "Frozen berries",
  "Frozen fries", "Frozen fries",
  "Frozen chicken nugget", "Frozen chicken nuggets",
  "Frozen fish", "Frozen fishes",
  "Frozen seafood", "Frozen seafoods",
  "Frozen meal", "Frozen meals",

  // Bread & Bakery
  "Bread", "Breads",
  "Whole wheat bread", "Whole wheat breads",
  "Sourdough bread", "Sourdough breads",
  "Bagel", "Bagels",
  "Croissant", "Croissants",
  "English muffin", "English muffins",
  "Tortilla", "Tortillas",
  "Cracker", "Crackers",

  // Snacks & Breakfast
  "Chip", "Chips",
  "Granola bar", "Granola bars",
  "Cereal", "Cereals",
  "Oatmeal", "Oatmeals",
  "Pancake mix", "Pancake mixes",
  "Maple syrup", "Maple syrups",
  "Honey", "Honeys",
  "Peanut butter", "Peanut butters",
  "Jam", "Jams",
  "Nutella", "Nutellas",

  // Beverages
  "Coffee", "Coffees",
  "Tea", "Teas",
  "Juice", "Juices",
  "Soda", "Sodas",
  "Bottled water", "Bottled waters",
  "Sports drink", "Sports drinks",
  "Beer", "Beers",
  "Wine", "Wines",
  "Spirit", "Spirits",

  // Pantry & Dry Goods
  "Condiment", "Condiments",
  "Salad dressing", "Salad dressings",
  "Spice", "Spices",
  "Pasta", "Pastas",
  "Rice", "Rices",
  "Lentil", "Lentils",
  "Canned bean", "Canned beans",
  "Canned vegetable", "Canned vegetables",
  "Canned fruit", "Canned fruits",
  "Canned soup", "Canned soups",
  "Baking supply", "Baking supplies",

  // Chicken Cuts
  "Whole chicken", "Whole chickens",
  "Chicken breast", "Chicken breasts",
  "Chicken thigh", "Chicken thighs",
  "Chicken drumstick", "Chicken drumsticks",
  "Chicken wing", "Chicken wings",
  "Chicken tender", "Chicken tenders",
  "Ground chicken", "Ground chickens",

  // Turkey Cuts
  "Whole turkey", "Whole turkeys",
  "Turkey breast", "Turkey breasts",
  "Turkey thigh", "Turkey thighs",
  "Turkey drumstick", "Turkey drumsticks",
  "Ground turkey", "Ground turkeys",

  // Beef Cuts
  "Ground beef", "Ground beefs",
  "Beef steak", "Beef steaks",
  "Ribeye steak", "Ribeye steaks",
  "T-bone steak", "T-bone steaks",
  "Sirloin steak", "Sirloin steaks",
  "Filet mignon", "Filet mignons",
  "Beef brisket", "Beef briskets",
  "Beef short rib", "Beef short ribs",
  "Beef roast", "Beef roasts",
  "Beef liver", "Beef livers",

  // Pork Cuts
  "Pork chop", "Pork chops",
  "Pork tenderloin", "Pork tenderloins",
  "Pork belly", "Pork bellies",
  "Pork shoulder", "Pork shoulders",
  "Ground pork", "Ground porks",
  "Pork rib", "Pork ribs",
  "Bacon", "Bacons",
  "Ham", "Hams",

  // Lamb Cuts
  "Lamb chop", "Lamb chops",
  "Lamb shank", "Lamb shanks",
  "Lamb shoulder", "Lamb shoulders",
  "Lamb rack", "Lamb racks",
  "Ground lamb", "Ground lambs",

  // Seafood
  "Salmon fillet", "Salmon fillets",
  "Tuna steak", "Tuna steaks",
  "Shrimp", "Shrimps",
  "Crab", "Crabs",
  "Lobster", "Lobsters",
  "Cod fillet", "Cod fillets",
  "Tilapia fillet", "Tilapia fillets"
];